### PR TITLE
[*] PDF : Update de.php of AEUC

### PR DESCRIPTION
**Pull request by Nobodaddy**
In parts outdated

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @Nobodaddy,

Thanks for your contribution. I add @AlexEven for review :)

Best regards,

**Comment by Nobodaddy** [comment]
Hi @tchauviere,
just tell Alex I simply updated to the levels of Crowdin.
Best wishes

**Comment by AlexEven** [comment]
It's all good, thanks Rainer!

**Comment by tchauviere** [comment]
Hi @Nobodaddy,

You PR is now merged.

Thanks for your contribution,

Best regards,

**Pull request merged**
