### PR TITLE
[*] BO: Update andvancedeucompliance.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
Some corrections to wording of descriptions in BO

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @Nobodaddy,

Thanks for your contribution, could you please make that PR on the dev branch instead ? Once it's done I'll merge it :)

Thanks a lot !

Regards,

**Comment by Nobodaddy** [comment]
Sorry, noticed this too late. Done.

**Comment by tchauviere** [comment]
I can't find another PR but this one (which is on master branch).
Can you check it again please ?

Thanks !

**Comment by Nobodaddy** [comment]
Most of the stuff is totally different in the dev version and doesn't need any improvement. Just line 74 left where I suggested a modification.

**Comment by tchauviere** [comment]
Oh ok,

Actually for modules, we always work on the dev branch and once we are ready, we merge it to master in order to be pushed directly to merchant BO (In case you would make some other PR in the future ;) )

I close this one then and take a look to line 74.

Regards,

**Comment by AlexEven** [comment]
Thanks @Nobodaddy 
I've taken into account your suggestion in this PR, although I had to adapt it:
https://github.com/PrestaShop/advancedeucompliance/pull/4

We can't exactly say merchants will be compliant thanks to this module (in the end, it remains their responsibility to be so), but rather that we're providing some tools for them to be compliant.

**Comment by Nobodaddy** [comment]
Of course you can't. It's fine by me. :)

**Pull request closed without merging**
