### PR TITLE
added "Enable/Disable" displaying checkbox for ToS

### PR DESCRIPTION
**Pull request by alexsimple**
added "Enable/Disable" displaying 'checkbox for ToS and notice fix which
appears 'cms_conditions' is not defined.

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @alexsimple:

Not sure to understand the purpose of it.
Is that meant to add another checkbox to the basic "TOS" checkbox when revocation terms are added to it ?

Thanks for these precisions !

**Comment by panploenes** [comment]
Hey
Its not a necessity to have the actual check box in the check out, at least in germany. So i think this commit allows us to choose if we want to display the check box or not.

**Comment by jBangiev** [comment]
He @tchauviere 
checkbox is not required, but the additional text must stay. This is the option from EU Legal.

**Comment by tchauviere** [comment]
Hi everyone !

Ok ! thanks for these precisions, I cant automatically merged this PR since some modifications had been done in-between making some conflicts. But I will integrate this option directly !

Again, thanks a lot for your lot :) 

Best regards,

**Pull request closed without merging**
