### PR TITLE
[*] Update de.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
File was neither complete nor up to date. I updated the German translations to the current version from Crowdin.

### CODE REVIEW

**Comment by Nobodaddy** [comment]
Ooops, Sorry! The following 2 items were onnly for test purposes:
+$_MODULE['<{advancedeucompliance}prestashop>advancedeucompliance_cac77d4c7de337f13ad1e89a8cecbc7f'] = 'Lieferzeit: 1 bis 3 Wochen';
+$_MODULE['<{advancedeucompliance}prestashop>advancedeucompliance_eeb992239a8454067cd7a47bbf0df359'] = 'Lieferzeit: 3 bis 6 Wochen';

The original translations should remain unchanged:
$_MODULE['<{advancedeucompliance}prestashop>advancedeucompliance_cac77d4c7de337f13ad1e89a8cecbc7f'] = 'Lieferzeit 1-2 Werktage';
$_MODULE['<{advancedeucompliance}prestashop>advancedeucompliance_eeb992239a8454067cd7a47bbf0df359'] = 'Lieferzeit 7-10 Werktage';

**Comment by AlexEven** [comment]
Hello Rainer, 

Apologies for the delay, I hadn't seen the PR. Thanks for the update!

Regarding your comment, would you mind making another commit to this branch to make sure these 2 translations remain unchanged? 

Thanks in advance,

**Comment by Nobodaddy** [comment]
Hello Alex,
never mind. Done!
https://github.com/PrestaShop/advancedeucompliance/compare/dev...Nobodaddy:patch-14

**Comment by AlexEven** [comment]
Just opened https://github.com/PrestaShop/advancedeucompliance/pull/42 with the updated file, closing this PR. Thanks!

**Pull request closed without merging**
